### ISSUE TITLE
What license is this code?

### ISSUE THREAD

**Issue by nirgal** [tachang/EyeFiServer#5]
Hello

Can you please specify under which license this code is released? Right now, it says "All right reserved" ...But I guess the fact you put it on github is for people to use it...

**Comment by nirgal** [comment]
https://code.google.com/p/eyefiserver/ says GPLv3, I hope this is ok with you :)

**Comment by tachang** [comment]
Correct. I released in under GPL.
On Jul 6, 2012 2:25 PM, "nirgal" <
reply@reply.github.com>
wrote:
